
name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Compilar exercícios
      run: |
        javac -d bin -sourcepath src src/ex01_tabuada/Tabuada.java src/ex02_imc/IMC.java src/ex03_pares_impares/ParesImpares.java src/ex04_divisibilidade/Divisibilidade.java

    - name: Testar Tabuada
      run: echo "5" | java -cp bin ex01_tabuada.Tabuada

    - name: Testar IMC
      run: echo "1.75 70" | java -cp bin ex02_imc.IMC

    - name: Testar Pares e Ímpares
      run: echo "1 10 1" | java -cp bin ex03_pares_impares.ParesImpares

    - name: Testar Divisibilidade
      run: printf "2\n4\n7\n" | java -cp bin ex04_divisibilidade.Divisibilidade